// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/custom/Alert.vue')['default']
    ArticleNavigation: typeof import('./components/structural/ArticleNavigation.vue')['default']
    ComponentBasics: typeof import('./components/examples/ComponentBasics.vue')['default']
    'IHeroiconsOutline:checkCircle': typeof import('~icons/heroicons-outline/check-circle')['default']
    'IHeroiconsOutline:code': typeof import('~icons/heroicons-outline/code')['default']
    'IHeroiconsOutline:exclamationCircle': typeof import('~icons/heroicons-outline/exclamation-circle')['default']
    'IHeroiconsOutline:informationCircle': typeof import('~icons/heroicons-outline/information-circle')['default']
    'IHeroiconsOutline:moon': typeof import('~icons/heroicons-outline/moon')['default']
    'IHeroiconsOutline:searchCircle': typeof import('~icons/heroicons-outline/search-circle')['default']
    'IHeroiconsOutline:sun': typeof import('~icons/heroicons-outline/sun')['default']
    'IHeroiconsOutline:xCircle': typeof import('~icons/heroicons-outline/x-circle')['default']
    'IHeroiconsSolid:chevronDown': typeof import('~icons/heroicons-solid/chevron-down')['default']
    'IHeroiconsSolid:chevronLeft': typeof import('~icons/heroicons-solid/chevron-left')['default']
    'IHeroiconsSolid:chevronRight': typeof import('~icons/heroicons-solid/chevron-right')['default']
    'IMdi:github': typeof import('~icons/mdi/github')['default']
    LeftArrow: typeof import('./components/icons/LeftArrow.vue')['default']
    Markdown: typeof import('./components/structural/Markdown.vue')['default']
    More: typeof import('./components/custom/More.vue')['default']
    NewsArticle: typeof import('./components/examples/NewsArticle.vue')['default']
    PopoverNavigation: typeof import('./components/structural/PopoverNavigation.vue')['default']
    PostList: typeof import('./components/structural/PostList.vue')['default']
    RightArrow: typeof import('./components/icons/RightArrow.vue')['default']
    SideNavigation: typeof import('./components/structural/SideNavigation.vue')['default']
    SiteHeader: typeof import('./components/structural/SiteHeader.vue')['default']
    Slides: typeof import('./components/custom/Slides.vue')['default']
    Title: typeof import('./components/custom/Title.vue')['default']
  }
}

export { }
